#!/bin/sh

MAXVEC=256
MINVEC=0
VECFILE=vectors.s

printf "# generated by vectors.sh - do not edit\n# handlers\n" > $VECFILE
printf ".intel_syntax noprefix\n" >> $VECFILE
printf ".global alltraps\n" >> $VECFILE

i=$MINVEC
while [ $i -lt $MAXVEC ]
do
	printf ".global vector$i\n" >> $VECFILE
	printf "vector$i:\n" >> $VECFILE
	printf '\tpush 0\n' >> $VECFILE
	printf "\tpush $i\n" >> $VECFILE
	printf '\tjmp alltraps\n' >> $VECFILE
	i="$((i+1))"
done

printf '\n# vector table\n' >> $VECFILE
printf '.data\n' >> $VECFILE
printf '.global vectors\n' >> $VECFILE
printf 'vectors:\n' >> $VECFILE

i=$MINVEC
while [ $i -lt $MAXVEC ]
do
	printf "\t.long vector$i\n" >> $VECFILE
	i="$((i+1))"
done
